package JOA.models.events;

public enum Type {
    ACHIEVEMENT,
    BEATMAP_PLAYCOUNT,
    BEATMAPSET_PLAYCOUNT,
    BEATMAPSET_DELETE,
    BEATMAPSET_UPDATE,
    RANK,
    RANK_LOST,
    USER_SUPPORT_AGAIN,
    USER_SUPPORT_FIRST,
    USER_SUPPORT_GIFT,
    USERNAME_CHANGE
}
